'use client';
import { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { Alert, Box, Button, Chip, CircularProgress, MenuItem, Paper, Stack, Tab, Tabs, TextField, Typography } from '@mui/material';
import { useAnalytics, useAnalyticsInsights } from '@/hooks/useAnalytics';
import { useCurrentUserRole } from '@/hooks/useAuthSession';
import { listarAssuntosPorDisciplina, listarDisciplinas, listarSubassuntosPorAssunto } from '@/services/catalogoService';
import { getApiErrorMessage } from '@/services/api';
import { AcquisitionFunnelPanel } from '@/components/analytics/AcquisitionFunnelPanel';
import type { AnalyticsFilters, AnalyticsRankingItem } from '@/services/analyticsService';

type Period=AnalyticsFilters['period']; type View='overview'|'funnel'|'activation'|'retention'|'content'|'quality';
const periods:Record<Period,string>={today:'Hoje','7d':'7 dias','30d':'30 dias',current_month:'Mês atual',custom:'Personalizado'};
const n=(v:number,decimals=0)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:decimals}).format(v);
const duration=(s:number)=>s<60?`${n(s)}s`:`${n(s/60,1)}min`;
function Metric({label,value,hint}:{label:string;value:string;hint?:string}){return <Paper variant="outlined" sx={{p:2.25,borderRadius:3,minHeight:120}}><Typography variant="body2" color="text.secondary" fontWeight={600}>{label}</Typography><Typography variant="h4" fontWeight={800} sx={{mt:1}}>{value}</Typography>{hint&&<Typography variant="caption" color="text.secondary">{hint}</Typography>}</Paper>}
function Cards({items}:{items:Array<[string,string,string?]>}){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(2,1fr)',lg:'repeat(4,1fr)'},gap:2}}>{items.map(([a,b,c])=><Metric key={a} label={a} value={b} hint={c}/>)}</Box>}
function Ranking({title,items}:{title:string;items:AnalyticsRankingItem[]}){const max=Math.max(...items.map(x=>x.total),1);return <Paper variant="outlined" sx={{p:2.5,borderRadius:3,minHeight:260}}><Typography variant="h6" fontWeight={750} mb={2}>{title}</Typography>{!items.length?<Typography color="text.secondary">Sem dados no período.</Typography>:<Stack spacing={1.5}>{items.map((x,i)=><Box key={`${x.id}-${x.label}-${i}`}><Stack direction="row" justifyContent="space-between"><Typography noWrap variant="body2">{x.label}</Typography><Typography variant="body2" fontWeight={700}>{n(x.total)}</Typography></Stack><Box sx={{height:6,bgcolor:'#edf1f7',borderRadius:8,mt:.5}}><Box sx={{height:'100%',width:`${Math.max(x.total/max*100,3)}%`,bgcolor:'primary.main',borderRadius:8}}/></Box></Box>)}</Stack>}</Paper>}
function RankingGrid({items}:{items:Array<[string,AnalyticsRankingItem[]]>}){return <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',lg:'repeat(2,1fr)'},gap:2}}>{items.map(([title,data])=><Ranking key={title} title={title} items={data}/>)}</Box>}
const healthStyle={GOOD:{label:'BOM',color:'#16803c',bg:'#eefbf2'},BAD:{label:'RUIM',color:'#b42318',bg:'#fff1f0'},STABLE:{label:'ESTÁVEL',color:'#175cd3',bg:'#eff8ff'},INSUFFICIENT_DATA:{label:'DADOS INSUFICIENTES',color:'#b54708',bg:'#fffaeb'}} as const;

export default function EstatisticasPage(){
 const role=useCurrentUserRole(); const [view,setView]=useState<View>('overview'); const [period,setPeriod]=useState<Period>('7d');
 const [startDate,setStart]=useState(''); const [endDate,setEnd]=useState(''); const [disciplinaId,setDisciplina]=useState<number>(); const [assuntoId,setAssunto]=useState<number>(); const [subassuntoId,setSubassunto]=useState<number>(); const [bancaId,setBanca]=useState<number>(); const [instituicaoId,setInstituicao]=useState<number>(); const [provaId,setProva]=useState<number>();
 const disciplinas=useQuery({queryKey:['catalogo','disciplinas'],queryFn:listarDisciplinas});
 const assuntos=useQuery({queryKey:['catalogo','assuntos',disciplinaId],queryFn:()=>listarAssuntosPorDisciplina(disciplinaId!),enabled:!!disciplinaId});
 const subassuntos=useQuery({queryKey:['catalogo','subassuntos',assuntoId],queryFn:()=>listarSubassuntosPorAssunto(assuntoId!),enabled:!!assuntoId});
 const filters=useMemo<AnalyticsFilters>(()=>({period,...(period==='custom'&&startDate&&endDate?{startDate,endDate}:{}),...(disciplinaId?{disciplinaId}:{}),...(assuntoId?{assuntoId}:{}),...(subassuntoId?{subassuntoId}:{}),...(bancaId?{bancaId}:{}),...(instituicaoId?{instituicaoId}:{}),...(provaId?{provaId}:{})}),[period,startDate,endDate,disciplinaId,assuntoId,subassuntoId,bancaId,instituicaoId,provaId]);
 const analytics=useAnalytics(filters); const insights=useAnalyticsInsights(filters); const d=analytics.data; const health=insights.data;
 if(role===null)return <Box p={4} textAlign="center"><CircularProgress/></Box>; if(role!=='ADMIN')return <Alert severity="error">Área exclusiva para administradores.</Alert>;
 return <Box sx={{p:{xs:2,md:4},maxWidth:1500,mx:'auto'}}>
  <Typography variant="h4" fontWeight={800}>Analytics</Typography><Typography color="text.secondary" mb={3}>Produto, estudo e qualidade dos eventos — atualização a cada 60 segundos.</Typography>
  <Paper variant="outlined" sx={{p:2.5,borderRadius:3,mb:3}}><Stack spacing={2}><Stack direction="row" gap={1} flexWrap="wrap">{Object.entries(periods).map(([key,label])=><Button key={key} size="small" variant={period===key?'contained':'outlined'} onClick={()=>setPeriod(key as Period)}>{label}</Button>)}</Stack>
   {period==='custom'&&<Stack direction={{xs:'column',sm:'row'}} spacing={1}><TextField type="date" size="small" label="Data inicial" value={startDate} onChange={e=>setStart(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/><TextField type="date" size="small" label="Data final" value={endDate} onChange={e=>setEnd(e.target.value)} slotProps={{inputLabel:{shrink:true}}}/></Stack>}
   <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:1.5}}>
    <TextField select size="small" label="Disciplina" value={disciplinaId??''} onChange={e=>{setDisciplina(e.target.value?+e.target.value:undefined);setAssunto(undefined);setSubassunto(undefined)}}><MenuItem value="">Todas</MenuItem>{(disciplinas.data??[]).map(x=><MenuItem key={x.id} value={x.id}>{x.nome}</MenuItem>)}</TextField>
    <TextField select size="small" label="Assunto" value={assuntoId??''} disabled={!disciplinaId} onChange={e=>{setAssunto(e.target.value?+e.target.value:undefined);setSubassunto(undefined)}}><MenuItem value="">Todos</MenuItem>{(assuntos.data??[]).map(x=><MenuItem key={x.id} value={x.id}>{x.nome}</MenuItem>)}</TextField>
    <TextField select size="small" label="Subassunto" value={subassuntoId??''} disabled={!assuntoId} onChange={e=>setSubassunto(e.target.value?+e.target.value:undefined)}><MenuItem value="">Todos</MenuItem>{(subassuntos.data??[]).map(x=><MenuItem key={x.id} value={x.id}>{x.nome}</MenuItem>)}</TextField>
    {[['Banca (ID)',bancaId,setBanca],['Instituição (ID)',instituicaoId,setInstituicao],['Prova (ID)',provaId,setProva]].map(([label,value,setter])=><TextField key={label as string} size="small" type="number" label={label as string} value={(value as number|undefined)??''} onChange={e=>(setter as (v:number|undefined)=>void)(e.target.value?+e.target.value:undefined)}/>)}
   </Box></Stack></Paper>
  {insights.isLoading&&<Paper variant="outlined" sx={{p:3,borderRadius:3,mb:3,textAlign:'center'}}><CircularProgress size={26}/></Paper>}
  {insights.isError&&<Alert severity="warning" sx={{mb:3}} action={<Button onClick={()=>insights.refetch()}>Tentar novamente</Button>}>O diagnóstico automático não pôde ser carregado. Os cards detalhados continuam disponíveis.</Alert>}
  {health&&<Paper variant="outlined" sx={{p:{xs:2.5,md:3},borderRadius:3,mb:3,borderColor:healthStyle[health.status].color,bgcolor:healthStyle[health.status].bg}}>
   <Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center" flexWrap="wrap"><Typography variant="h5" fontWeight={800}>Saúde do app</Typography><Chip label={healthStyle[health.status].label} size="small" sx={{fontWeight:800,color:'white',bgcolor:healthStyle[health.status].color}}/></Stack><Typography variant="h3" fontWeight={900} color={healthStyle[health.status].color} mt={1}>{health.score}/100</Typography><Typography fontWeight={700}>{health.scoreChangePercent==null?'Sem base anterior':`${health.scoreChangePercent>0?'+':''}${n(health.scoreChangePercent,1)}% vs período anterior`}</Typography></Box><Box sx={{maxWidth:760}}><Typography variant="h6" fontWeight={800}>{health.title}</Typography><Typography color="text.secondary">{health.summary}</Typography><Typography variant="body2" mt={1}><b>Confiança:</b> {{HIGH:'Alta',MEDIUM:'Média',LOW:'Baixa'}[health.confidence]} — {health.confidenceReason}</Typography></Box></Stack>
   {health.possibleAutomatedTraffic&&<Alert severity="warning" sx={{mt:2}}>{health.automatedTrafficReason}</Alert>}
   <Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:3,mt:3}}><Box><Typography fontWeight={800} mb={1}>Principais sinais</Typography><Stack spacing={1}>{health.drivers.map((driver,i)=><Box key={`${driver.metric}-${i}`}><Typography variant="body2" fontWeight={700} color={driver.type==='positive'?'success.main':driver.type==='negative'?'error.main':'warning.main'}>{driver.type==='positive'?'✓':'⚠'} {driver.title}</Typography><Typography variant="caption" color="text.secondary">{driver.description}</Typography></Box>)}</Stack></Box><Box><Typography fontWeight={800} mb={1}>Recomendações</Typography><Stack spacing={1}>{health.recommendations.map((item,i)=><Box key={`${item.relatedMetric}-${i}`}><Typography variant="body2" fontWeight={700}>{i+1}. {item.title}</Typography><Typography variant="caption" color="text.secondary">{item.description}</Typography></Box>)}</Stack></Box></Box>
  </Paper>}
  <Tabs value={view} onChange={(_,v)=>setView(v)} variant="scrollable" sx={{mb:3}}>{[['overview','Visão geral'],['funnel','Funil de aquisição'],['activation','Ativação'],['retention','Retenção'],['content','Conteúdo'],['quality','Qualidade dos dados']].map(([v,l])=><Tab key={v} value={v} label={l}/>)}</Tabs>
  {analytics.isLoading&&<Box py={8} textAlign="center"><CircularProgress/></Box>}{analytics.isError&&<Alert severity="error" action={<Button onClick={()=>analytics.refetch()}>Tentar novamente</Button>}>{getApiErrorMessage(analytics.error,'Falha ao carregar analytics.')}</Alert>}
  {d&&view==='overview'&&<Stack spacing={3}><Cards items={[["Ativos hoje",n(d.overview.activeToday)],["Online agora",n(d.overview.onlineNow),`Últimos ${d.onlineWindowMinutes} min`],["Ativos reais",n(d.overview.realActive),'Responderam ao menos uma questão'],["Sessões",n(d.overview.sessions)],["Questões hoje",n(d.overview.questionsToday)],["Questões no período",n(d.overview.questionsPeriod)],["Duração média",duration(d.overview.averageSessionSeconds)],["Acurácia média",`${n(d.overview.averageAccuracy,1)}%`],["Dispositivos",n(d.overview.devices)],["Usuários identificados",n(d.overview.identifiedUsers)]]}/><Paper variant="outlined" sx={{p:2,borderRadius:3,overflowX:'auto'}}><Typography variant="h6" mb={1}>Tendência diária</Typography><Stack direction="row" spacing={1} minWidth={600}>{d.dailyTrend.map(x=><Box key={x.date} sx={{flex:1,textAlign:'center',p:1,bgcolor:'action.hover',borderRadius:2}}><Typography variant="caption">{new Date(x.date+'T12:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</Typography><Typography fontWeight={800}>{n(x.questions)}</Typography><Typography variant="caption">questões</Typography></Box>)}</Stack></Paper></Stack>}
  {d&&view==='funnel'&&(d.acquisitionFunnel?<AcquisitionFunnelPanel funnel={d.acquisitionFunnel}/>:<Alert severity="info">A API ainda não disponibilizou dados do funil neste ambiente.</Alert>)}
  {d&&view==='activation'&&<Stack spacing={3}><Cards items={[["Novas identidades",n(d.activation.newIdentities)],["Abriram o app",n(d.activation.appOpened)],["Primeira questão vista",n(d.activation.firstQuestionViewed)],["Primeira resposta",n(d.activation.firstQuestionAnswered)],["Taxa de ativação",`${n(d.activation.activationRate,1)}%`],["Tempo até responder",`${n(d.activation.averageMinutesToFirstAnswer,1)}min`],["Questões / ativo",n(d.engagement.questionsPerActive,1)],["Sessões / ativo",n(d.engagement.sessionsPerActive,1)],["Ativos ≥ 10",n(d.engagement.identitiesWith10Questions)],["Ativos ≥ 50",n(d.engagement.identitiesWith50Questions)],["Engajados em 7 dias",n(d.engagement.engagedLast7Days)],["Usuários inativos",n(d.engagement.inactiveUsers)]]}/></Stack>}
  {d&&view==='retention'&&<Stack spacing={2}><Cards items={[["Retenção D1",`${n(d.retention.day1,1)}%`],["Retenção D7",`${n(d.retention.day7,1)}%`],["Retenção D30",`${n(d.retention.day30,1)}%`]]}/><Alert severity="info">{d.retention.method}</Alert></Stack>}
  {d&&view==='content'&&<Stack spacing={2}><Cards items={[["Filtros sem resultado",n(d.content.filtersWithoutResults)],["Buscas sem resultado",n(d.content.searchesWithoutResults)]]}/><RankingGrid items={[["Telas mais acessadas",d.content.topScreens],["Filtros mais usados",d.content.topFilters],["Disciplinas acessadas",d.content.disciplinesAccessed],["Disciplinas respondidas",d.content.disciplinesAnswered],["Assuntos acessados",d.content.subjectsAccessed],["Assuntos respondidos",d.content.subjectsAnswered],["Subassuntos acessados",d.content.subsubjectsAccessed],["Subassuntos respondidos",d.content.subsubjectsAnswered],["Questões com mais erros",d.content.mostWrongQuestions],["Questões com mais acertos",d.content.mostCorrectQuestions]]}/></Stack>}
  {d&&view==='quality'&&<Stack spacing={3}><Cards items={[["Eventos nas últimas 24h",n(d.dataQuality.eventsLast24Hours)],["Eventos desconhecidos",n(d.dataQuality.unknownEvents)],["Sem sessão",`${n(d.dataQuality.missingSessionPercent,1)}%`],["Sem identidade",`${n(d.dataQuality.missingIdentityPercent,1)}%`],["Último evento",d.dataQuality.lastEventAt?new Date(d.dataQuality.lastEventAt).toLocaleString('pt-BR'):'Nenhum'] ]}/><Ranking title="Erros recentes" items={d.dataQuality.recentErrors}/><Paper variant="outlined" sx={{p:2,borderRadius:3}}><Typography variant="h6">Eventos por versão</Typography>{Object.entries(d.dataQuality.eventsByAppVersion).map(([v,total])=><Typography key={v}>{v}: <b>{n(total)}</b></Typography>)}</Paper></Stack>}
 </Box>
}
